### ISSUE TITLE
xing模块缺失问题

### ISSUE THREAD

**Issue by kevinsnameneedlong** [TophantTechnology/ARL#172]
[root@root ARL-2.3.1]# gunicorn -b 0.0.0.0:5003 app.main:arl_app -w 3 --access-logfile arl_web.log
[2021-07-08 13:19:24 +0800] [22958] [INFO] Starting gunicorn 19.9.0
[2021-07-08 13:19:24 +0800] [22958] [INFO] Listening at: http://0.0.0.0:5003 (22958)
[2021-07-08 13:19:24 +0800] [22958] [INFO] Using worker: sync
[2021-07-08 13:19:24 +0800] [22961] [INFO] Booting worker with pid: 22961
[2021-07-08 13:19:24 +0800] [22962] [INFO] Booting worker with pid: 22962
[2021-07-08 13:19:24 +0800] [22963] [INFO] Booting worker with pid: 22963
[2021-07-08 13:19:26 +0800] [22961] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/ARL/ARL-2.3.1/app/main.py", line 4, in <module>
    from app import routes
  File "/opt/ARL/ARL-2.3.1/app/routes/__init__.py", line 216, in <module>
    from .task import ns as task_ns
  File "/opt/ARL/ARL-2.3.1/app/routes/task.py", line 5, in <module>
    from app import celerytask
  File "/opt/ARL/ARL-2.3.1/app/celerytask.py", line 7, in <module>
    from app import tasks as wrap_tasks
  File "/opt/ARL/ARL-2.3.1/app/tasks/__init__.py", line 1, in <module>
    from .domain import domain_task, add_domain_to_scope
  File "/opt/ARL/ARL-2.3.1/app/tasks/domain.py", line 8, in <module>
    from app import  services
  File "/opt/ARL/ARL-2.3.1/app/services/__init__.py", line 21, in <module>
    from .npoc import run_risk_cruising, run_sniffer
  File "/opt/ARL/ARL-2.3.1/app/services/npoc.py", line 3, in <module>
    from xing.core import PluginType, PluginRunner
ModuleNotFoundError: No module named 'xing'
[2021-07-08 13:19:26 +0800] [22961] [INFO] Worker exiting (pid: 22961)
[2021-07-08 13:19:26 +0800] [22963] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/ARL/ARL-2.3.1/app/main.py", line 4, in <module>
    from app import routes
  File "/opt/ARL/ARL-2.3.1/app/routes/__init__.py", line 216, in <module>
    from .task import ns as task_ns
  File "/opt/ARL/ARL-2.3.1/app/routes/task.py", line 5, in <module>
    from app import celerytask
  File "/opt/ARL/ARL-2.3.1/app/celerytask.py", line 7, in <module>
    from app import tasks as wrap_tasks
  File "/opt/ARL/ARL-2.3.1/app/tasks/__init__.py", line 1, in <module>
    from .domain import domain_task, add_domain_to_scope
  File "/opt/ARL/ARL-2.3.1/app/tasks/domain.py", line 8, in <module>
    from app import  services
  File "/opt/ARL/ARL-2.3.1/app/services/__init__.py", line 21, in <module>
    from .npoc import run_risk_cruising, run_sniffer
  File "/opt/ARL/ARL-2.3.1/app/services/npoc.py", line 3, in <module>
    from xing.core import PluginType, PluginRunner
ModuleNotFoundError: No module named 'xing'
[2021-07-08 13:19:26 +0800] [22963] [INFO] Worker exiting (pid: 22963)
[2021-07-08 13:19:26 +0800] [22962] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/ARL/ARL-2.3.1/app/main.py", line 4, in <module>
    from app import routes
  File "/opt/ARL/ARL-2.3.1/app/routes/__init__.py", line 216, in <module>
    from .task import ns as task_ns
  File "/opt/ARL/ARL-2.3.1/app/routes/task.py", line 5, in <module>
    from app import celerytask
  File "/opt/ARL/ARL-2.3.1/app/celerytask.py", line 7, in <module>
    from app import tasks as wrap_tasks
  File "/opt/ARL/ARL-2.3.1/app/tasks/__init__.py", line 1, in <module>
    from .domain import domain_task, add_domain_to_scope
  File "/opt/ARL/ARL-2.3.1/app/tasks/domain.py", line 8, in <module>
    from app import  services
  File "/opt/ARL/ARL-2.3.1/app/services/__init__.py", line 21, in <module>
    from .npoc import run_risk_cruising, run_sniffer
  File "/opt/ARL/ARL-2.3.1/app/services/npoc.py", line 3, in <module>
    from xing.core import PluginType, PluginRunner
ModuleNotFoundError: No module named 'xing'
[2021-07-08 13:19:26 +0800] [22962] [INFO] Worker exiting (pid: 22962)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 210, in run
    self.sleep()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[root@molika ARL-2.3.1]# pip3 install xing
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement xing (from versions: none)
ERROR: No matching distribution found for xing

**Comment by 1c3z** [comment]
现在文档有点缺失，是这个。 

https://github.com/1c3z/ARL-NPoC

**Comment by kevinsnameneedlong** [comment]
已解决，谢谢！

**Comment by myxss** [comment]
> 已解决，谢谢！
怎么解决的老哥

**Comment by 1c3z** [comment]
> > 已解决，谢谢！
> > 怎么解决的老哥

可以看下这个文档， 后面的更新过程中提供了个源码安装的脚本。
https://github.com/TophantTechnology/ARL#%E6%BA%90%E7%A0%81%E5%AE%89%E8%A3%85
