### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by invoke888** [TophantTechnology/ARL#366]
[2022-08-03 12:21:29,681: ERROR/ForkPoolWorker-2] ???[???]: list index out of range
Traceback (most recent call last):
  File "/opt/ARL-NPoC/xing/core/BaseThread.py", line 23, in _work
    self.work(url)
  File "/opt/ARL-NPoC/xing/core/BruteRunner.py", line 26, in work
    result = self.plg.login(self.target, user=user, passwd=pwd)
  File "/opt/ARL-NPoC/xing/plugins/brute/MysqlBrute.py", line 26, in login
    plugin, scramble = get_scramble(data)
  File "/opt/ARL-NPoC/xing/plugins/brute/MysqlBrute.py", line 78, in get_scramble
    scramble = m[0] + m[1]
IndexError: list index out of range
[2022-08-03 12:21:29,681: ERROR/ForkPoolWorker-2] ???[???]: list index out of range
Traceback (most recent call last):
  File "/opt/ARL-NPoC/xing/core/BaseThread.py", line 23, in _work
    self.work(url)
  File "/opt/ARL-NPoC/xing/core/BruteRunner.py", line 26, in work
    result = self.plg.login(self.target, user=user, passwd=pwd)
  File "/opt/ARL-NPoC/xing/plugins/brute/MysqlBrute.py", line 26, in login
    plugin, scramble = get_scramble(data)
  File "/opt/ARL-NPoC/xing/plugins/brute/MysqlBrute.py", line 78, in get_scramble
    scramble = m[0] + m[1]
IndexError: list index out of range

**Comment by 1c3z** [comment]
收到

**Comment by 1c3z** [comment]
已修复。
