### ISSUE TITLE
arl_work arl_web arl_scheduler  restarting 

### ISSUE THREAD

**Issue by haoyes0v0** [TophantTechnology/ARL#391]
启动docker总是restarting，请问怎么解决
```
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                          PORTS                                                                  NAMES
035f148685e9   tophant/arl:latest                  "sh -c 'wait-for-it.…"   35 minutes ago   Restarting (1) 24 seconds ago                                                                          arl_worker
0b0a70940c85   tophant/arl:latest                  "sh -c 'gen_crt.sh; …"   35 minutes ago   Restarting (1) 10 seconds ago                                                                          arl_web
164343de9253   tophant/arl:latest                  "sh -c 'wait-for-it.…"   35 minutes ago   Restarting (1) 10 seconds ago                                                                          arl_scheduler
daf7b7999679   mongo:4.0.27                        "docker-entrypoint.s…"   35 minutes ago   Up About a minute               27017/tcp                                                              arl_mongodb
f749ba3b56fb   rabbitmq:3.8.19-management-alpine   "docker-entrypoint.s…"   35 minutes ago   Up About a minute               4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 15691-15692/tcp, 25672/tcp   arl_rabbitmq

```
docker-compose logs
```
arl_scheduler | wait-for-it.sh: waiting 15 seconds for mongodb:27017
arl_mongodb  | 2022-09-04T12:53:45.452+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:41208 #55 (1 connection now open)
arl_mongodb  | 2022-09-04T12:53:45.453+0000 I NETWORK  [conn55] end connection 172.18.0.2:41208 (0 connections now open)
arl_scheduler | wait-for-it.sh: mongodb:27017 is available after 0 seconds
arl_web      | wait-for-it.sh: waiting 15 seconds for mongodb:27017
arl_mongodb  | 2022-09-04T12:53:45.587+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:42556 #56 (1 connection now open)
arl_mongodb  | 2022-09-04T12:53:45.587+0000 I NETWORK  [conn56] end connection 172.18.0.3:42556 (0 connections now open)
arl_web      | wait-for-it.sh: mongodb:27017 is available after 0 seconds
arl_scheduler | Traceback (most recent call last):
arl_scheduler |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
arl_scheduler |     return _run_code(code, main_globals, None,
arl_scheduler |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
arl_scheduler |     exec(code, run_globals)
arl_scheduler |   File "/code/app/scheduler.py", line 3, in <module>
arl_scheduler |     from app.utils import conn_db as conn
arl_scheduler |   File "/code/app/utils/__init__.py", line 204, in <module>
arl_scheduler |     from .user import user_login, user_login_header, auth, user_logout, change_pass
arl_scheduler |   File "/code/app/utils/user.py", line 1, in <module>
arl_scheduler |     from flask import  request
arl_scheduler |   File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
arl_scheduler |     from jinja2 import Markup, escape
arl_scheduler | ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
arl_web      | [2022-09-04 20:53:45 +0800] [24] [INFO] Starting gunicorn 20.1.0
arl_web      | [2022-09-04 20:53:45 +0800] [24] [INFO] Listening at: http://0.0.0.0:5003 (24)
arl_web      | [2022-09-04 20:53:45 +0800] [24] [INFO] Using worker: sync
arl_web      | [2022-09-04 20:53:45 +0800] [26] [INFO] Booting worker with pid: 26
arl_web      | [2022-09-04 20:53:45 +0800] [26] [ERROR] Exception in worker process
arl_web      | Traceback (most recent call last):
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
arl_web      |     worker.init_process()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
arl_web      |     self.load_wsgi()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
arl_web      |     self.wsgi = self.app.wsgi()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
arl_web      |     self.callable = self.load()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
arl_web      |     return self.load_wsgiapp()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
arl_web      |     return util.import_app(self.app_uri)
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
arl_web      |     mod = importlib.import_module(module)
arl_web      |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
arl_web      |     return _bootstrap._gcd_import(name[level:], package, level)
arl_web      |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
arl_web      |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
arl_web      |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
arl_web      |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
arl_web      |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
arl_web      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
arl_web      |   File "/code/app/main.py", line 1, in <module>
arl_web      |     from flask import Flask
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
arl_web      |     from jinja2 import Markup, escape
arl_web      | ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
arl_web      | [2022-09-04 20:53:45 +0800] [26] [INFO] Worker exiting (pid: 26)
arl_web      | [2022-09-04 20:53:45 +0800] [27] [INFO] Booting worker with pid: 27
arl_web      | [2022-09-04 20:53:45 +0800] [27] [ERROR] Exception in worker process
arl_web      | Traceback (most recent call last):
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
arl_web      |     worker.init_process()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
arl_web      |     self.load_wsgi()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
arl_web      |     self.wsgi = self.app.wsgi()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
arl_web      |     self.callable = self.load()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
arl_web      |     return self.load_wsgiapp()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
arl_web      |     return util.import_app(self.app_uri)
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
arl_web      |     mod = importlib.import_module(module)
arl_web      |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
arl_web      |     return _bootstrap._gcd_import(name[level:], package, level)
arl_web      |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
arl_web      |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
arl_web      |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
arl_web      |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
arl_web      |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
arl_web      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
arl_web      |   File "/code/app/main.py", line 1, in <module>
arl_web      |     from flask import Flask
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
arl_web      |     from jinja2 import Markup, escape
arl_web      | ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
arl_web      | [2022-09-04 20:53:45 +0800] [27] [INFO] Worker exiting (pid: 27)
arl_scheduler exited with code 1
arl_web      | Traceback (most recent call last):
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 202, in run
arl_web      |     self.manage_workers()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 551, in manage_workers
arl_web      |     self.spawn_workers()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 623, in spawn_workers
arl_web      |     time.sleep(0.1 * random.random())
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
arl_web      |     self.reap_workers()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
arl_web      |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
arl_web      | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
arl_web      | 
arl_web      | During handling of the above exception, another exception occurred:
arl_web      | 
arl_web      | Traceback (most recent call last):
arl_web      |   File "/usr/local/bin/gunicorn", line 8, in <module>
arl_web      |     sys.exit(run())
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
arl_web      |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 231, in run
arl_web      |     super().run()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 72, in run
arl_web      |     Arbiter(self).run()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 229, in run
arl_web      |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 342, in halt
arl_web      |     self.stop()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 393, in stop
arl_web      |     time.sleep(0.1)
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
arl_web      |     self.reap_workers()
arl_web      |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
arl_web      |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
arl_web      | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
arl_web exited with code 1
arl_worker   | wait-for-it.sh: waiting 15 seconds for mongodb:27017
arl_mongodb  | 2022-09-04T12:53:51.931+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:41220 #57 (1 connection now open)
arl_mongodb  | 2022-09-04T12:53:51.931+0000 I NETWORK  [conn57] end connection 172.18.0.2:41220 (0 connections now open)
arl_worker   | wait-for-it.sh: mongodb:27017 is available after 0 seconds
arl_worker   | wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
arl_rabbitmq | 2022-09-04 12:53:51.943 [info] <0.882.0> Closing all channels from connection '172.18.0.2:50898 -> 172.18.0.6:5672' because it has been closed
arl_worker   | wait-for-it.sh: rabbitmq:5672 is available after 0 seconds
arl_worker   | Traceback (most recent call last):
arl_worker   |   File "/usr/local/bin/celery", line 8, in <module>
arl_worker   |     sys.exit(main())
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/__main__.py", line 16, in main
arl_worker   |     _main()
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/celery.py", line 322, in main
arl_worker   |     cmd.execute_from_commandline(argv)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
arl_worker   |     super(CeleryCommand, self).execute_from_commandline(argv)))
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 273, in execute_from_commandline
arl_worker   |     argv = self.setup_app_from_commandline(argv)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
arl_worker   |     self.app = self.find_app(app)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 501, in find_app
arl_worker   |     return find_app(app, symbol_by_name=self.symbol_by_name)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/app/utils.py", line 359, in find_app
arl_worker   |     sym = symbol_by_name(app, imp=imp)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 504, in symbol_by_name
arl_worker   |     return imports.symbol_by_name(name, imp=imp)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/kombu/utils/imports.py", line 57, in symbol_by_name
arl_worker   |     module = imp(module_name, package=package, **kwargs)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/utils/imports.py", line 104, in import_from_cwd
arl_worker   |     return imp(module, package=package)
arl_worker   |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
arl_worker   |     return _bootstrap._gcd_import(name[level:], package, level)
arl_worker   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
arl_worker   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
arl_worker   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
arl_worker   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
arl_worker   |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
arl_worker   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
arl_worker   |   File "/code/app/celerytask.py", line 6, in <module>
arl_worker   |     from app import utils
arl_worker   |   File "/code/app/utils/__init__.py", line 204, in <module>
arl_worker   |     from .user import user_login, user_login_header, auth, user_logout, change_pass
arl_worker   |   File "/code/app/utils/user.py", line 1, in <module>
arl_worker   |     from flask import  request
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
arl_worker   |     from jinja2 import Markup, escape
arl_worker   | ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
arl_worker   | Traceback (most recent call last):
arl_worker   |   File "/usr/local/bin/celery", line 8, in <module>
arl_worker   |     sys.exit(main())
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/__main__.py", line 16, in main
arl_worker   |     _main()
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/celery.py", line 322, in main
arl_worker   |     cmd.execute_from_commandline(argv)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
arl_worker   |     super(CeleryCommand, self).execute_from_commandline(argv)))
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 273, in execute_from_commandline
arl_worker   |     argv = self.setup_app_from_commandline(argv)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
arl_worker   |     self.app = self.find_app(app)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 501, in find_app
arl_worker   |     return find_app(app, symbol_by_name=self.symbol_by_name)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/app/utils.py", line 359, in find_app
arl_worker   |     sym = symbol_by_name(app, imp=imp)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 504, in symbol_by_name
arl_worker   |     return imports.symbol_by_name(name, imp=imp)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/kombu/utils/imports.py", line 57, in symbol_by_name
arl_worker   |     module = imp(module_name, package=package, **kwargs)
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/celery/utils/imports.py", line 104, in import_from_cwd
arl_worker   |     return imp(module, package=package)
arl_worker   |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
arl_worker   |     return _bootstrap._gcd_import(name[level:], package, level)
arl_worker   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
arl_worker   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
arl_worker   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
arl_worker   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
arl_worker   |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
arl_worker   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
arl_worker   |   File "/code/app/celerytask.py", line 6, in <module>
arl_worker   |     from app import utils
arl_worker   |   File "/code/app/utils/__init__.py", line 204, in <module>
arl_worker   |     from .user import user_login, user_login_header, auth, user_logout, change_pass
arl_worker   |   File "/code/app/utils/user.py", line 1, in <module>
arl_worker   |     from flask import  request
arl_worker   |   File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
arl_worker   |     from jinja2 import Markup, escape
arl_worker   | ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
arl_worker exited with code 1


```
docker version

```
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:11:41 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       20.10.12-0ubuntu4
  Built:            Mon Mar  7 15:57:50 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu3
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

```

**Comment by Mr-xn** [comment]
是不是服务器配置不过 或者 网络原因 可以 重新 down 掉 再启

**Comment by haoyes0v0** [comment]
>
OK了解

**Comment by 1c3z** [comment]
@haoyes0v0 

ARM镜像已经更新了
