### ISSUE TITLE
rabbitmq连接拒绝怎么办

### ISSUE THREAD

**Issue by Pinus97** [TophantTechnology/ARL#423]
求助
ERROR/MainProcess] consumer: Cannot connect to amqp://arl:**@rabbitmq:5672/arlv2host: [Errno 111] Connection refused
![image](https://user-images.githubusercontent.com/103227912/197934555-63b7a725-44a9-4b8b-859e-f9fec1a6f75d.png)

**Comment by 1c3z** [comment]
1. 排查下rabbitmq 容器状态 `docker ps`
2. 进入worker 容器 ，ping rabbitmq 看可以通么。
3. 或者重建容器
```
docker-compose down
docker-compose up -d
```
4.或者重装，参考下面 #389

**Comment by Pinus97** [comment]
@1c3z 现在变成这种情况了
![image](https://user-images.githubusercontent.com/103227912/197954407-c8581688-347a-46cc-886f-e6a70d2daea8.png)

**Comment by tonmonkey** [comment]
我的也产生这种问题，这是arl_worker.log日志：
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-11-10 13:40:34,938: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 521, in on_inbound_method
    method_sig, payload, content,
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 649, in _on_close
    self._x_close_ok()
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 664, in _x_close_ok
    self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 189, in write_frame
    write(view[:offset])
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 305, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-11-10 13:40:35,020: ERROR/MainProcess] consumer: Cannot connect to amqp://arl:**@rabbitmq:5672/arlv2host: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2022-11-10 13:40:35,022: ERROR/MainProcess] consumer: Cannot connect to amqp://arl:**@rabbitmq:5672/arlv2host: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

**Comment by 1c3z** [comment]
@tonmonkey 

旧的系统，原先的没有down导致的么？

https://github.com/TophantTechnology/ARL/issues/380
