### ISSUE TITLE
报错：字典在迭代期间改变了大小

### ISSUE THREAD

**Issue by cloud-jie** [TophantTechnology/ARL#425]
dictionary changed size during iteration
Traceback (most recent call last):
  File "/code/app/tasks/domain.py", line 961, in domain_task
    d.run()
  File "/code/app/tasks/domain.py", line 942, in run
    self.domain_fetch()
  File "/code/app/tasks/domain.py", line 785, in domain_fetch
    self.domain_brute()
  File "/code/app/tasks/domain.py", line 523, in domain_brute
    domain_info_list = domain_brute(self.base_domain, word_file=self.domain_word_file)
  File "/code/app/tasks/domain.py", line 371, in domain_brute
    return b.run()
  File "/code/app/tasks/domain.py", line 98, in run
    for domain in self.resolver_map:
RuntimeError: dictionary changed size during iteration

**Comment by 1c3z** [comment]
改过代码么？ 
试了下可以的。 

![image](https://user-images.githubusercontent.com/9052484/198222464-a99d5387-1780-4a11-9475-d2d782697676.png)

**Comment by cloud-jie** [comment]
> 改过代码么？ 试了下可以的。
> 
> ![image](https://user-images.githubusercontent.com/9052484/198222464-a99d5387-1780-4a11-9475-d2d782697676.png)

没改过代码
好不容易运行成功了，又有了些新的错误

**Comment by 1c3z** [comment]
@cloud-jie 

提供的日志，里面的报错是正常的。 

任务运行完毕了，跑了24个站点。
