### ISSUE TITLE
Python3.6.8请求一些https网站时报 ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:852) 错误

### ISSUE THREAD

**Issue by TARI0510** [TophantTechnology/ARL#473]
使用的是 docker 版本

在ARL层面，表现为获取不到任何站点，原本可以收集到很多信息的。

进入容器内，通过 Python requests 请求该网站报错
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/39155974/214550932-2a4ff409-c6d8-404b-9485-716615c3303a.png">
完整报错
```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:877)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxxx.com', port=443): Max retries exceeded with url: /dashboard/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='xxxxx.com', port=443): Max retries exceeded with url: /dashboard/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:877)'),))
>>> print(res.content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'res' is not defined
>>> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:877)
  File "<stdin>", line 1
    ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:877)
```

已尝试的解决方案
https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol
https://github.com/pypa/pip/issues/4205
均无效

我本机的Python3.6.8也是报这个错，升级至3.7，可正常请求
<img width="718" alt="image" src="https://user-images.githubusercontent.com/39155974/214551632-a72714d1-47b3-4150-a497-46197d3553bc.png">

站点为项目URL，打码了，需要可私聊。问题应该是 Centos7 官方的Python3.6包编译安装一些编译选项导致 ssl 功能异常

师傅们打算怎么解决这个问题呀？目前我想到的是修改 Dockerfile 通过 yum 安装 Python3.6 为 编译安装 3.7 新点版本，或者是试试还是装 Python3.6，试试这里 https://github.com/pypa/pip/issues/4205#issuecomment-269735544 的编译选项

**Comment by 1c3z** [comment]
很强。

运行时的 arl_work 日志，不过没抛出啥异常，有点奇怪，

我把requests的错误都屏蔽了。
https://github.com/TophantTechnology/ARL/blob/master/app/services/baseThread.py#L23

**Comment by 1c3z** [comment]
我需要目标测试下，麻烦加下这个群吧。
![image](https://user-images.githubusercontent.com/9052484/215392478-908e989c-2e74-4e02-8aba-ad22e1d39ea9.png)

**Comment by TARI0510** [comment]
> 很强。
> 
> 运行时的 arl_work 日志，不过没抛出啥异常，有点奇怪，
> 
> 我把requests的错误都屏蔽了。 https://github.com/TophantTechnology/ARL/blob/master/app/services/baseThread.py#L23

怪不得
