### ISSUE TITLE
异常错误所有列表都是error

### ISSUE THREAD

**Issue by xiaosanzhang66** [TophantTechnology/ARL#530]
这种情况是端口扫描挂了吗？有没办法解决啊大牛

poc_sites:2
[2023-04-10 07:47:15,681: WARNING/ForkPoolWorker-1] app.celerytask.arl_task[37e49eaf-ae00-4fb5-9b36-608c1629015a]: not found nuclei
[2023-04-10 07:47:15,682: ERROR/ForkPoolWorker-1] app.celerytask.arl_task[37e49eaf-ae00-4fb5-9b36-608c1629015a]: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/ARL/app/tasks/domain.py", line 1073, in domain_task
    d.run()
  File "/opt/ARL/app/tasks/domain.py", line 1057, in run
    self.start_site_fetch()
  File "/opt/ARL/app/tasks/domain.py", line 895, in start_site_fetch
    web_site_fetch.run()
  File "/opt/ARL/app/services/commonTask.py", line 296, in run
    self.run_func(WebSiteFetchStatus.NUCLEI_SCAN, self.nuclei_scan)
  File "/opt/ARL/app/services/commonTask.py", line 252, in run_func
    func()
  File "/opt/ARL/app/services/commonTask.py", line 241, in nuclei_scan
    for item in scan_results:
TypeError: 'NoneType' object is not iterable
[2023-04-10 07:47:15,688: INFO/ForkPoolWorker-1] app.celerytask.arl_task[37e49eaf-ae00-4fb5-9b36-608c1629015a]: end domain_task elapsed: 3032.9866104125977
[2023-04-10 07:47:15,690: INFO/ForkPoolWorker-1] Task app.celerytask.arl_task[37e49eaf-ae00-4fb5-9b36-608c1629015a] succeeded in 3032.9894932870084s: None

**Comment by xiaosanzhang66** [comment]
看了别人反馈的说机器内存小挂了，我机器4核6G理论上不应该挂才对

**Comment by 1c3z** [comment]
源码安装的么？ 
没有安装nuclei ， 版本要小于2.9.1

**Comment by viplurker** [comment]
> Reference i

这个问题我也遇到了，怎么感觉源码安装总有点奇怪的情况产生....
