### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by shen771** [TophantTechnology/ARL#628]
## 描述问题

启动docker报错ascii' codec can't decode byte 0xe6 in position 278: ordinal not in range

## 环境信息

- 操作系统：centos7
- Docker版本：Docker version 1.13.1,
- ARL 版本:v2.5.5

### 错误输出

请执行以下命令，并提供输出结果：

```
[root@ixxxxxxxx docker]# docker-compose up -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.18.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 121, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 37, in project_from_options
    override_dir=options.get('--project-directory'),
  File "/usr/lib/python3.6/site-packages/compose/cli/command.py", line 87, in get_project
    config_details = config.find(project_dir, config_path, environment, override_dir)
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 278, in find
    [ConfigFile.from_filename(f) for f in filenames],
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 278, in <listcomp>
    [ConfigFile.from_filename(f) for f in filenames],
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 178, in from_filename
    return cls(filename, load_yaml(filename))
  File "/usr/lib/python3.6/site-packages/compose/config/config.py", line 1305, in load_yaml
    return yaml.safe_load(fh)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/usr/local/lib64/python3.6/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib64/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 278: ordinal not in range(128)
[root@ixxxxxx docker]# echo $LANG
zh_CN.UTF-8

```

**Comment by 1c3z** [comment]
1. 看起来是中文的原因，把 docker-compose.yml 里面的中文删除了试试。
2. 用docker compose up -d 试试 （新版本docker 带了 compose）

**Comment by shen771** [comment]
看起来是中文的原因，把 docker-compose.yml 里面的中文删除了试试。

实测有效
