### ISSUE TITLE
mongdb restart

### ISSUE THREAD

**Issue by xjp08** [TophantTechnology/ARL#663]
docker ps
![image](https://github.com/TophantTechnology/ARL/assets/104262157/70b7528a-def0-4f6e-b3b1-8948c429c9b3)
mongdb一直重启
然后查看日志：
2023-11-20 09:25:20] [INFO] [MainThread] [scheduler.py:220] start scheduler server 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/app/scheduler.py", line 237, in <module>
    run_forever()
  File "/code/app/scheduler.py", line 223, in run_forever
    asset_monitor_scheduler()
  File "/code/app/scheduler.py", line 185, in asset_monitor_scheduler
    for item in all_job():
  File "/code/app/scheduler.py", line 128, in all_job
    for item in conn('scheduler').find():
  File "/usr/local/lib64/python3.6/site-packages/pymongo/cursor.py", line 1280, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib64/python3.6/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 2027, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 1976, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 2013, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib64/python3.6/site-packages/pymongo/topology.py", line 525, in get_server_session
    session_timeout = self._check_session_support()
  File "/usr/local/lib64/python3.6/site-packages/pymongo/topology.py", line 508, in _check_session_support
    any_server_selector, self._settings.server_selection_timeout, None
  File "/usr/local/lib64/python3.6/site-packages/pymongo/topology.py", line 228, in _select_servers_loop
    % (self._error_message(selector), timeout, self.description)
pymongo.errors.ServerSelectionTimeoutError: mongodb:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 655ab58071579b3dbc0cc812, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -2] Name or service not known',)>]>
wait-for-it.sh: waiting 15 seconds for mongodb:27017
wait-for-it.sh: timeout occurred after waiting 15 seconds for mongodb:27017
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 0 seconds

**Comment by 1c3z** [comment]
没看到mongo 容器的报错日志。

执行下面的看看
```
docker logs -f arl_mongodb 
```

**Comment by xjp08** [comment]
> docker logs -f arl_mongodb

2023-11-20T03:49:40.999+0000 E STORAGE  [initandlisten] WiredTiger error (-31802) [1700452180:999487][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 571: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error Raw: [1700452180:999487][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 571: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error
2023-11-20T03:49:40.999+0000 E STORAGE  [initandlisten] WiredTiger error (0) [1700452180:999543][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 577: WiredTiger has failed to open its metadata Raw: [1700452180:999543][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 577: WiredTiger has failed to open its metadata
2023-11-20T03:49:40.999+0000 E STORAGE  [initandlisten] WiredTiger error (0) [1700452180:999559][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 581: This may be due to the database files being encrypted, being from an older version or due to corruption on disk Raw: [1700452180:999559][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 581: This may be due to the database files being encrypted, being from an older version or due to corruption on disk
2023-11-20T03:49:40.999+0000 E STORAGE  [initandlisten] WiredTiger error (0) [1700452180:999565][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 585: You should confirm that you have opened the database with the correct options including all encryption and compression options Raw: [1700452180:999565][1:0x7f1261a1da80], file:WiredTiger.wt, connection: __wt_btree_tree_open, 585: You should confirm that you have opened the database with the correct options including all encryption and compression options
2023-11-20T03:49:41.000+0000 W STORAGE  [initandlisten] Failed to start up WiredTiger under any compatibility version.
2023-11-20T03:49:41.000+0000 W STORAGE  [initandlisten] WiredTiger metadata corruption detected
2023-11-20T03:49:41.000+0000 F STORAGE  [initandlisten] Please read the documentation for starting MongoDB with --repair here: http://dochub.mongodb.org/core/repair
2023-11-20T03:49:41.000+0000 F -        [initandlisten] Fatal Assertion 50944 at src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 705
2023-11-20T03:49:41.000+0000 F -        [initandlisten] \n\n***aborting after fassert() failure\n\n

**Comment by 1c3z** [comment]
看着像数据库损坏了，删了重装试试吧。

```
docker volume rm arl_db
```

https://tophanttechnology.github.io/ARL-doc/faq/#11-docker
