### ISSUE TITLE
使用时报NetworkError错误,然后访问不了web页面

### ISSUE THREAD

**Issue by thinkoaa** [TophantTechnology/ARL#69]
arl设置如图:
![settings](https://user-images.githubusercontent.com/65639454/103155978-2c36cc80-47df-11eb-99dc-070f0aa3e882.png)
虚拟机配置如图:
![hardware](https://user-images.githubusercontent.com/65639454/103155988-39ec5200-47df-11eb-987c-96337656eac2.png)
任务列表如图:
![list](https://user-images.githubusercontent.com/65639454/103156002-5ab4a780-47df-11eb-9fe8-cbefa615cb50.png)
报错信息如图,刷新的话直接访问不了web界面了:
![NetworkError](https://user-images.githubusercontent.com/65639454/103156007-61431f00-47df-11eb-990b-db25c796efc0.png)
docker查看后台容器如图:
![dockerps](https://user-images.githubusercontent.com/65639454/103156014-6dc77780-47df-11eb-988d-b7576e07d138.png)

**Comment by 1c3z** [comment]
感觉是卡了，可以看下虚拟机CPU使用情况。

**Comment by thinkoaa** [comment]
报错信息如下:
![Snipaste_2020-12-28_22-00-54](https://user-images.githubusercontent.com/65639454/103219292-3c25ec00-4958-11eb-9ebb-6d8286e12000.png)

**Comment by thinkoaa** [comment]
上面的报错信息问题暂时解决了:
ARL/docker目录下把arl_worker.log和arl_web.log两个文件夹改成文件即可

**Comment by thinkoaa** [comment]
日志如图,有些多:
![++](https://user-images.githubusercontent.com/65639454/103220031-34ffdd80-495a-11eb-9770-4927d94a6f3f.png)
![+++](https://user-images.githubusercontent.com/65639454/103220035-36310a80-495a-11eb-8db6-bb29fee3bed5.png)

**Comment by 1c3z** [comment]
我在日志里看到了 docker-compose 连接也有点问题。。 
可能在域名爆破过程中带宽有点大。虚拟机可以尝试切换成桥接模式看下。

**Comment by thinkoaa** [comment]
切换了桥接试了试还是不行,
看到有rabbitmq错误,不知道是否是这原因.
==> arl_worker.log <==
[2020-12-30 15:09:47,938: ERROR/MainProcess] consumer: Cannot connect to amqp://arl:**@rabbitmq:5672/arlv2host: [Errno 111] Connection refused.
Trying again in 14.00 seconds...

[2020-12-30 15:10:01,970: ERROR/MainProcess] consumer: Cannot connect to amqp://arl:**@rabbitmq:5672/arlv2host: [Errno 111] Connection refused.
Trying again in 16.00 seconds...

**Comment by 1c3z** [comment]
这个是没连上rabbitmq,   执行下docker-compose ps 看下容器状态。

最开始的那个图，感觉容器重启过了。

**Comment by thinkoaa** [comment]
刚才带都试了试,还是不行,应该就是虚拟机里面发包太快导致的,发包速度或线程数有地方改吗,或者web界面提供一个设置参数的功能:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/log_printer.py", line 169, in tail_container_logs
    queue.put(QueueItem.new(presenter.color_func(wait_on_exit(container))))
  File "/usr/lib/python3/dist-packages/compose/cli/log_printer.py", line 200, in wait_on_exit
    exit_code = container.wait()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 281, in wait
    return self.client.wait(self.id).get('StatusCode', 127)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1289, in wait
    res = self._post(url, timeout=timeout, params=params)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 226, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by 1c3z** [comment]
可以进入worker容器，尝试修改下面这行。重启容器后生效。
https://github.com/TophantTechnology/ARL/blob/master/app/services/massdns.py#L34

**Comment by thinkoaa** [comment]
每个容器都修改了,改成5也不行,等以后更新了再用用看.

**Comment by 1c3z** [comment]
本地复测了下，没有发现问题

![image](https://user-images.githubusercontent.com/9052484/103768100-d672e780-505c-11eb-93ad-1505c65eabb1.png)

![image](https://user-images.githubusercontent.com/9052484/103768175-0621ef80-505d-11eb-87cb-2a7b30d5d340.png)

**Comment by 1c3z** [comment]
@thinkoaa   先关闭issue
