### ISSUE TITLE
centos源码安装修改配置文件config-docker.yaml，执行python3.6 -m test.test_query_plugin 1 2报错

### ISSUE THREAD

**Issue by lll377** [TophantTechnology/ARL#700]
## 描述问题

请在此处提供对问题的清晰而简洁的描述。

## 环境信息
系统环境
- 操作系统：centos 7
- Docker版本：
- ARL 版本:

### 错误输出

请执行以下命令，并提供输出结果：
修改配置文件dingding
执行命令
python3.6 -m test.test_query_plugin 1 2

报错
[root@HK-7X54 ARL]# python3.6 -m test.test_query_plugin 1 2
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ARL/test/test_query_plugin.py", line 4, in <module>
    from app.services.dns_query import run_query_plugin
  File "/opt/ARL/app/services/__init__.py", line 23, in <module>
    from .domainSiteUpdate import domain_site_update
  File "/opt/ARL/app/services/domainSiteUpdate.py", line 5, in <module>
    from app.helpers.domain import find_domain_by_task_id
  File "/opt/ARL/app/helpers/__init__.py", line 2, in <module>
    from .task import submit_task, build_task_data, get_ip_domain_list, submit_task_task, submit_risk_cruising
  File "/opt/ARL/app/helpers/task.py", line 5, in <module>
    from app import celerytask
  File "/opt/ARL/app/celerytask.py", line 7, in <module>
    from app import tasks as wrap_tasks
  File "/opt/ARL/app/tasks/__init__.py", line 1, in <module>
    from .domain import domain_task
  File "/opt/ARL/app/tasks/domain.py", line 17, in <module>
    from app.services import domain_site_update
ImportError: cannot import name 'domain_site_update'

四个服务分别都重启过

**Comment by 1c3z** [comment]
感谢反馈，导入有点问题。 
可以先在test_query_plugin.py 前面加上。
```
from app import celerytask
```


#699

**Comment by lll377** [comment]
我是用的源码安装方式系统是centos 7.6 ARL是2.61 我是在opt/ARL/app目录下配置文件修改config.yaml，增加钉钉 SECRET: 
  ACCESS_TOKEN: 这个值后，再进行测试python3.6 -m test.test_query_plugin报错，而且配置没生效，

**Comment by lll377** [comment]
[root@0fcb476636af code]# python3.6 -m test.test_query_plugin
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/test/test_query_plugin.py", line 4, in <module>
    from app.services.dns_query import run_query_plugin
  File "/code/app/services/__init__.py", line 23, in <module>
    from .domainSiteUpdate import domain_site_update
  File "/code/app/services/domainSiteUpdate.py", line 5, in <module>
    from app.helpers.domain import find_domain_by_task_id
  File "/code/app/helpers/__init__.py", line 2, in <module>
    from .task import submit_task, build_task_data, get_ip_domain_list, submit_task_task, submit_risk_cruising
  File "/code/app/helpers/task.py", line 5, in <module>
    from app import celerytask
  File "/code/app/celerytask.py", line 7, in <module>
    from app import tasks as wrap_tasks
  File "/code/app/tasks/__init__.py", line 1, in <module>
    from .domain import domain_task
  File "/code/app/tasks/domain.py", line 17, in <module>
    from app.services import domain_site_update
ImportError: cannot import name 'domain_site_update'  还是报错！

**Comment by 1c3z** [comment]
没改好。可以数下这个是第几行。 from app.services.dns_query import run_query_plugin


<img width="1057" alt="image" src="https://github.com/TophantTechnology/ARL/assets/9052484/4daf6be0-e60a-4d8a-8579-cfc5d9214544">

**Comment by lll377** [comment]
我在config_docker.yaml 我增加了钉钉配置，这个地方该如何配置，有示例吗？是不是必须配置了才会定期推送钉钉消息。
--------
WXWORK:
  WEBHOOK_URL: ""

# 监控任务 WEBHOOK 配置
# IP/域名监控和站点监控结束后会往下面的URL POST提交JSON数据
# 为了验证身份会在Header中带上Token 字段
# 进入容器测试  docker-compose exec worker bash
# 测试命令 python3.6 -m test.test_webhook <task_id> <scope_id>
WEBHOOK:
  URL: ""
  TOKEN: ""

--------

这没看明白
监控任务自定义 WEBHOOK 功能[¶](https://tophanttechnology.github.io/ARL-doc/config_option/#webhook)
可以在config-docker.yaml WEBHOOK选项下配置

IP/域名监控和站点监控结束后会往配置的webhook URL POST提交JSON数据

为了验证身份会在Header中带上Token 字段, 接收方可以验证Token字段是否符合预期

进入容器测试 docker-compose exec worker bash

测试命令 python3.6 -m test.test_webhook <task_id> <scope_id>

如果没有传递source参数，那么就会全部测试。

测试完毕后重启容器生效。

-----------------

python3.6 -m test.test_utils_push
[2024-01-12 13:23:33] [INFO] [MainThread] [fetchSite.py:99] start fetch site 2
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[2024-01-12 13:23:38] [INFO] [MainThread] [fetchSite.py:102] end fetch site elapse 4.656367063522339
[2024-01-12 13:23:38] [INFO] [MainThread] [buildDomainInfo.py:40] start build Domain info 2
[2024-01-12 13:23:38] [INFO] [MainThread] [buildDomainInfo.py:43] end build Domain info 2 elapse 0.20224237442016602
[2024-01-12 13:23:39] [INFO] [MainThread] [push.py:177] push dingding succ
[2024-01-12 13:23:39] [INFO] [MainThread] [buildDomainInfo.py:40] start build Domain info 2
[2024-01-12 13:23:39] [INFO] [MainThread] [buildDomainInfo.py:43] end build Domain info 2 elapse 0.20288658142089844
[2024-01-12 13:23:39] [INFO] [MainThread] [portScan.py:60] nmap target 1.1.1.1  ports 80,443,8443,8080,808  arguments -sT -n --open -Pn --max-rtt-timeout 800ms --min-rate 64 --script-timeout 6s --max-hostgroup 32 --host-timeout 300s --min-parallelism 32 --max-retries 3
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[2024-01-12 13:23:40] [INFO] [MainThread] [push.py:177] push dingding succ
.FFF
======================================================================
FAIL: test_push_email (__main__.TestUtilsPush)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/test_utils_push.py", line 111, in test_push_email
    self.assert_email_config()
  File "/code/test/test_utils_push.py", line 89, in assert_email_config
    self.assertTrue(Config.EMAIL_PASSWORD)
AssertionError: '' is not true

======================================================================
FAIL: test_push_feishu (__main__.TestUtilsPush)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/test_utils_push.py", line 122, in test_push_feishu
    self.assert_feishu_config()
  File "/code/test/test_utils_push.py", line 93, in assert_feishu_config
    self.assertTrue(Config.FEISHU_SECRET)
AssertionError: '' is not true

======================================================================
FAIL: test_wx_work_push (__main__.TestUtilsPush)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/test_utils_push.py", line 133, in test_wx_work_push
    self.assert_wx_work_config()
  File "/code/test/test_utils_push.py", line 97, in assert_wx_work_config
    self.assertTrue(Config.WX_WORK_WEBHOOK)
AssertionError: '' is not true

----------------------------------------------------------------------
Ran 4 tests in 6.425s

FAILED (failures=3)

**Comment by 1c3z** [comment]
v2.6.2 已修复
