### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by fanygit** [TophantTechnology/ARL#727]
## 描述问题
源码安装  运行报错error
![image](https://github.com/TophantTechnology/ARL/assets/42337082/a1d4a897-4ad5-4e3a-97be-fbf7c31f3731)

## 环境信息

- 操作系统：
- Docker版本：
- ARL 版本:

### 错误输出

```
[2024-02-17 23:00:57,341: INFO/ForkPoolWorker-3] app.celerytask.arl_task[cb84937d-eb73-43e8-8777-1f19e0734adf]: search_engines gxdlxy.edu.cn, result domain:0 url:0
[2024-02-17 23:00:57,359: INFO/ForkPoolWorker-3] app.celerytask.arl_task[cb84937d-eb73-43e8-8777-1f19e0734adf]: start port_scan 4
[2024-02-17 23:00:57,359: INFO/ForkPoolWorker-3] app.celerytask.arl_task[cb84937d-eb73-43e8-8777-1f19e0734adf]: nmap target 222.203.241.9 222.20  ports 1,3-4,6-7,9,13,17,19  arguments -sT -n --open -PE -PS22,80,443,843,3389,8007-8011,8443,9090,8080-8091,8093,8099,5000-5004,2222,3306,1433,21,25 --max-rtt-timeout 800ms --min-rate 64 --script-timeout 6s --max-hostgroup 32 --host-timeout 300s --min-parallelism 32 --max-retries 2
[2024-02-17 23:00:57,374: ERROR/ForkPoolWorker-3] app.celerytask.arl_task[cb84937d-eb73-43e8-8777-1f19e0734adf]: "nmap: unrecognized option '--script-timeout'\n"
Traceback (most recent call last):
  File "/opt/ARL/app/utils/nmap.py", line 323, in analyse_nmap_xml_scan
    dom = ET.fromstring(self._nmap_last_output)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ARL/app/tasks/domain.py", line 1084, in domain_task
    d.run()
  File "/opt/ARL/app/tasks/domain.py", line 1064, in run
    self.start_ip_fetch()
  File "/opt/ARL/app/tasks/domain.py", line 868, in start_ip_fetch
    self.port_scan()
  File "/opt/ARL/app/tasks/domain.py", line 666, in port_scan
    ip_info_list = scan_port(self.domain_info_list, self.scan_port_option)
  File "/opt/ARL/app/tasks/domain.py", line 388, in scan_port
    return s.run()
  File "/opt/ARL/app/tasks/domain.py", line 194, in run
    ip_port_result = services.port_scan(all_ipv4_list, **self.option)
  File "/opt/ARL/app/services/portScan.py", line 113, in port_scan
    return ps.run()
  File "/opt/ARL/app/services/portScan.py", line 62, in run
    nm.scan(hosts=self.targets, ports=self.ports, arguments=self.nmap_arguments)
  File "/opt/ARL/app/utils/nmap.py", line 268, in scan
    nmap_warn_keep_trace=nmap_warn_keep_trace
  File "/opt/ARL/app/utils/nmap.py", line 326, in analyse_nmap_xml_scan
    raise PortScannerError(nmap_err)
app.utils.nmap.PortScannerError: "nmap: unrecognized option '--script-timeout'\n"
[2024-02-17 23:00:57,377: INFO/ForkPoolWorker-3] app.celerytask.arl_task[cb84937d-eb73-43e8-8777-1f19e0734adf]: end domain_task elapsed: 27.129080533981323
[2024-02-17 23:00:57,377: INFO/ForkPoolWorker-3] Task app.celerytask.arl_task[cb84937d-eb73-43e8-8777-1f19e0734adf] succeeded in 27.129480263218284s: None
```

**Comment by 1c3z** [comment]
nmap 版本有点低，要升级下。
